### ISSUE TITLE
[Feature Request] Short URL for OONI Run link

### ISSUE THREAD

**Issue by bact** [ooni/run#164] opened 2024-05-10 02:49 UTC
If OONI Run can generate a shorter URL, it will be easier to share the link.

- Social media platforms, like Instagram Stories, limit the length of the URL.

- Putting the URL on an image for social media sharing also has to mind about it's length (as the space is limited and we don't want to use too small font).

- It is also quite invasive to share a long link in a group chat. X (Twitter) is now also show the URL in full, which can make the post quite overwhelming.

- Long URLs tend to break easily as well.

See also #39

**Comment by bact** [comment] 2024-05-12 13:33
See #39

**Comment by jbonisteel** [comment] 2024-07-12 14:59
I am going to close this because it is a duplicate of: https://github.com/ooni/run/issues/39 

And OONI Run v2 will have shorter links.

**Closed by jbonisteel** 2024-07-12 14:59 UTC
