### ISSUE TITLE
Internal Server Error on Firefox Klar

### ISSUE THREAD

**Issue by anadahz** [ooni/run#23] opened 2019-03-19 17:47 UTC
I get an `Internal Server Error` on Firefox Klar version `6.1.1` (Build `#22`) when trying to open any OONI run link.

Workaround: Enable `Request desktop site` option in Firefox Klar config.

**Comment by hellais** [comment] 2019-03-19 18:27
Can you provide a screenshot of the error message or more information about what is displayed on your screen when the error is displayed?

The content of your browser User-Agent string would also be useful.

**Comment by anadahz** [comment] 2019-03-19 19:19
> Can you provide a screenshot of the error message or more information about what is displayed on your screen when the error is displayed?

Screenshot:
![Screenshot](https://user-images.githubusercontent.com/4969544/54635325-ca7af780-4a7b-11e9-8877-20b0a85590c0.png)

> The content of your browser User-Agent string would also be useful.

User-Agent:
```
Mozilla/5.0 (Linux; Android 7.1.2) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/6.1.1 Chrome/63.0.3239.111 Mobile Safari/537.36
Browser Name: Chrome
Browser OS (Operating System):Android
63.0.3239.111
```

**Comment by hellais** [comment] 2019-03-19 19:25
Thanks for the update. For some reason that user-agent string identifies the browser as belonging to the "Chrome Mobile" browser family. Can you also share the exact OONI Run link you used?

**Comment by anadahz** [comment] 2019-03-19 19:40
OONI Run link used: https://run.ooni.io/nettest?tn=http_invalid_request_line&mv=1.2.0

**Comment by hellais** [comment] 2019-03-19 20:02
Ok I was able to reproduce the bug on run.ooni.io by running:
```
curl -A 'Mozilla/5.0 (Linux; Android 7.1.2) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/6.1.1 Chrome/63.0.3239.111 Mobile Safari/537.36' 'run.ooni.io/nettest?tn=http_invalid_request_line&mv=1.2.0'
```

It was however not happening with the version of ooni-run in master. It appears that this was an issue in the OONI Run deployment.

The issue is now fixed on run.ooni.io.

Related: https://github.com/ooni/sysadmin/issues/278.

**Closed by hellais** 2019-03-19 20:02 UTC
