### ISSUE TITLE
Provide links to "ready made" OONI Run links via the OONI Run homepage

### ISSUE THREAD

**Issue by agrabeli** [ooni/run#93] opened 2021-12-21 14:36 UTC
During the OONI Partner Training 2021, participants mentioned that it would be helpful if the main OONI Run homepage provided links to "ready made" OONI Run links to help them get started. These could include, for example, OONI Run links to test popular social media websites.

**Comment by hellais** [comment] 2022-01-31 09:00
This is a duplicate of: https://github.com/ooni/run/issues/86.

Closing.

**Closed by hellais** 2022-01-31 09:00 UTC
Labels: duplicate, user feedback, partner training 2021
