### ISSUE TITLE
Support running OONI Run links with the OONI Probe desktop app

### ISSUE THREAD

**Issue by agrabeli** [ooni/run#88] opened 2021-12-21 14:23 UTC
During the OONI Partner Training 2021, participants mentioned that it would be useful if users could also run OONI Run links from the **OONI Probe desktop app** (instead of just mobile). This feedback was also shared by participants of the OONI Run usability study.

**Comment by hellais** [comment] 2022-01-31 08:58
This is a duplicate of: https://github.com/ooni/probe/issues/1071.
Closing.

**Closed by hellais** 2022-01-31 08:58 UTC
Labels: duplicate, enhancement, user feedback, partner training 2021
