### ISSUE TITLE
Enable users to find measurements from OONI Run links

### ISSUE THREAD

**Issue by agrabeli** [ooni/run#98] opened 2021-12-21 15:15 UTC
During the OONI Partner Training 2021, participants mentioned that it's hard to find measurements pertaining to specific OONI Run links. 

Perhaps if OONI Run links have measurement IDs, that would enable data analysis. But it would also be helpful to have an easier way of finding such measurements (for non-data-analysts). This would greatly support research and advocacy efforts.

**Comment by hellais** [comment] 2022-01-31 09:03
This is a duplicate of: https://github.com/ooni/run/issues/95 & ooni/probe#818

**Closed by hellais** 2022-01-31 09:03 UTC
Labels: user feedback, partner training 2021
