### ISSUE TITLE
Improve OONI Run

### ISSUE THREAD

**Issue by agrabeli** [ooni/run#58] opened 2021-05-03 16:50 UTC
This epic tracks improvements to the OONI Run platform based on community feedback shared as part of our OONI Run Usability Study: https://ooni.org/post/2020-06-09-ooni-run-usability-study-findings/

**Comment by hellais** [comment] 2021-06-09 15:05
This is a duplicate of: https://github.com/ooni/ooni.org/issues/346

**Closed by hellais** 2021-06-09 15:05 UTC
Labels: epic
